//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.06.11 at 11:30:34 AM CEST
//
package main.diff_L1_L2.delta;

//import java.math.int;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAnyElement;
//import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.w3c.dom.Element;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "insert")
public class Insert {

    @XmlAttribute(name = "at", required = true)
    protected int at;
    @XmlAttribute(name = "nodecount", required = true)
    protected int nodecount;
    @XmlAttribute(name = "nodenumber", required = true)
    protected int nodenumber;
    @XmlAttribute(name = "pos", required = true)
    protected int pos;
    @XmlAnyElement
    protected Element[] elements;
    //    @XmlValue
//    protected String value;

    /**
     * Gets the value of the at property.
     *
     * @return possible object is {@link int }
     *
     */
    public int getAt() {
        return at;
    }

    /**
     * Sets the value of the at property.
     *
     * @param value allowed object is {@link int }
     *
     */
    public void setAt(int value) {
        this.at = value;
    }

    /**
     * Gets the value of the nodecount property.
     *
     * @return possible object is {@link int }
     *
     */
    public int getNodecount() {
        return nodecount;
    }

    /**
     * Sets the value of the nodecount property.
     *
     * @param value allowed object is {@link int }
     *
     */
    public void setNodecount(int value) {
        this.nodecount = value;
    }

    /**
     * Gets the value of the nodenumber property.
     *
     * @return possible object is {@link int }
     *
     */
    public int getNodenumber() {
        return nodenumber;
    }

    /**
     * Sets the value of the nodenumber property.
     *
     * @param value allowed object is {@link int }
     *
     */
    public void setNodenumber(int value) {
        this.nodenumber = value;
    }

    /**
     * Gets the value of the pos property.
     *
     * @return possible object is {@link int }
     *
     */
    public int getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     *
     * @param value allowed object is {@link int }
     *
     */
    public void setPos(int value) {
        this.pos = value;
    }

    public Element[] getElements() {
        return elements;
    }

    public void setElements(Element[] elements) {
        this.elements = elements;
    }

//    public String getValue() {
//        return value;
//    }
//
//    public void setValue(String value) {
//        this.value = value;
//    }
    /**
     *
     * @return String
     */
    @Override
    public String toString() {
        return new ToStringBuilder(this).
                append("\nat ", at).
                append("\nnumber ", nodenumber).
                append("\nnodecount ", nodecount).
                append("\npos ", pos).
                //                append("\nvalue ", value).
                toString();
    }

}
